name: Addon Linter
on:
  push:
    branches: [ master ]
    paths:
      - 'haos-jellyfin/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'haos-jellyfin/**'

jobs:
  lint:
    if: contains(github.repository, 'haos-jellyfin')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Home Assistant Add-on Linter
        shell: bash
        run: |
          docker run --rm -i \
            -v $(pwd)/haos-jellyfin:/addon \
            -v $(pwd)/.github/linter-config.yaml:/config.yaml:ro \
            -e ADDON_PATH=/addon \
            jrmio/ha-addon-linter:latest || true
